// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPgFj2G8bipS5N7nRSYNdxa8MuPrhMKaM',
    appId: '1:77287722969:web:f384cdc6d78f1b878e93c8',
    messagingSenderId: '77287722969',
    projectId: 'fa22se19-oms',
    authDomain: 'fa22se19-oms.firebaseapp.com',
    storageBucket: 'fa22se19-oms.appspot.com',
    measurementId: 'G-E5TWP4T7NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqtMFITXT59hlPRkn4X0AyBDM5WDBIv84',
    appId: '1:77287722969:android:2222afc561c5009f8e93c8',
    messagingSenderId: '77287722969',
    projectId: 'fa22se19-oms',
    storageBucket: 'fa22se19-oms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC93Skj6jnEYzKVAx4nKHkIlLn2jiPel_Q',
    appId: '1:77287722969:ios:a2f4c16f1950464f8e93c8',
    messagingSenderId: '77287722969',
    projectId: 'fa22se19-oms',
    storageBucket: 'fa22se19-oms.appspot.com',
    iosClientId: '77287722969-b4bsokt88l7chrf1jl5bn1u2k26tfs5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.omsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC93Skj6jnEYzKVAx4nKHkIlLn2jiPel_Q',
    appId: '1:77287722969:ios:a2f4c16f1950464f8e93c8',
    messagingSenderId: '77287722969',
    projectId: 'fa22se19-oms',
    storageBucket: 'fa22se19-oms.appspot.com',
    iosClientId: '77287722969-b4bsokt88l7chrf1jl5bn1u2k26tfs5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.omsMobile',
  );
}
